# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Ensure Clean Jupyter Notebooks
        # You may pin to the exact commit or the version.
        # uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@e22cb52580930a21c3121a44c9e67fa37e149121
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
